language: node_js
sudo: required
node_js:
  - "node"
branch: master
cache:
  directories:
    - node_modules
after_success:
    - npm run build
    - cd docs/.vuepress/dist
    - git init
    - git add -A
    - git commit -m 'deploy'
    - git push -f https://${access_token}@github.com/tudousdk/tudousdk.github.io.git master
